name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1  
        with:
          toolchain: nightly
      - name: Cargo Test
        run: |
          cargo test --all --verbose
